[workspace]


members = ["common", "barretenberg_wasm", "barretenberg_static_lib", "aztec_backend_wasm"]
# barretenberg_js will be phased out in the future

# exclude = ["aztec_backend_wasm"]

exclude = ["barretenberg_js"]

authors = ["The Noir Team <kevtheappdev@gmail.com>"]
edition = "2021"
rust-version = "1.66"
license = "MIT OR Apache-2.0"