[package]
name = "common"
version = "0.1.0"
authors.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
acvm = { version = "0.9.0", features = ["bn254"] }
sled = "0.34.6"
blake2 = "0.9.1"
dirs = { version = "3.0", optional = true }
downloader = { version = "0.2.7", optional = true, default-features = false, features = ["rustls-tls"] }
indicatif = { version = "0.15.0", optional = true }
wasm-bindgen = { version = "0.2.84", features = ["serde-serialize"], optional = true }
wasm-bindgen-futures = { version = "0.4.34", optional = true }
web-sys = { version = "0.3.61", optional = true, features = ["Headers", "Request", "RequestInit", "RequestMode", "Response", "Window", "ServiceWorkerGlobalScope"] }
js-sys = { version = "0.3.61", optional = true }
log = "0.4.17"
wasm-logger = "0.2.0"

[features]
# This feature flag is here because we cannot compile
# the downloader dependency with the wasm32 target
default = ["js"]
std = ["dep:downloader", "dep:dirs", "dep:indicatif"]
js = ["dep:wasm-bindgen", "dep:wasm-bindgen-futures", "dep:js-sys" , "dep:web-sys"]

