[package]
name = "common"
version = "0.1.0"
authors.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
acvm = { git = "https://github.com/noir-lang/acvm", rev = "7043b62d84503fa288ebde4d82cbede01d5490d9" }

sled = "0.34.6"
blake2 = "0.9.1"
dirs = { version = "3.0", optional = true }
downloader = { version = "0.2.7", optional = true, default-features = false, features = ["rustls-tls"] }
indicatif = { version = "0.15.0", optional = true }
regex = "1.4.0"

[features]
# This feature flag is here because we cannot compile
# the downloader dependency with the wasm32 target
default = ["std"]
std = ["dep:downloader", "dep:dirs", "dep:indicatif"]
